Remove windows binary building which is not needed
and also fails to build with error:

```
  ⨯ release failed after 3m17s               error=failed to build for windows_amd64_v1: exit status 1: go: downloading github.com/kairos-io/kairos-sdk v0.0.17
...
package github.com/kairos-io/provider-kairos/v2
	imports github.com/kairos-io/provider-kairos/v2/internal/cli
	imports github.com/kairos-io/kairos-agent/v2/pkg/config
	imports github.com/kairos-io/kairos-agent/v2/pkg/utils/partitions
	imports github.com/jaypipes/ghw/pkg/linuxpath: build constraints exclude all Go files in /home/runner/go/pkg/mod/github.com/jaypipes/ghw@v0.12.0/pkg/linuxpath

Error: The process '/opt/hostedtoolcache/goreleaser-action/1.22.1/x64/goreleaser' failed with exit code 1
```

Failure introduced here: 2d5ff88

Signed-off-by: Dimitris Karakasilis <dimitris@karakasilis.me>